trigger:
  branches:
    include:
      - main

variables:
  APP_NAME: 'human-resources-service'
  CONTAINER_REG: 'salasmicroservicesacr'
  WEB_APP: 'api-integration-ms'
  RESOURCE_GROUP: 'data-management-group'
  BUILD_ID: $(Build.BuildId)

stages:
  - stage: Deploy
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy Docker Image to Azure Web App'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              docker run --rm \
                -e AZURE_SUBSCRIPTION_ID=$(AZURE_SUBSCRIPTION_ID) \
                -e AZURE_CLIENT_ID=$(AZURE_CLIENT_ID) \
                -e AZURE_CLIENT_SECRET=$(AZURE_CLIENT_SECRET) \
                -e AZURE_TENANT_ID=$(AZURE_TENANT_ID) \
                mcr.microsoft.com/azure-cli:latest \
                /bin/bash -c "
                  az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
                  az webapp config container set --name $WEB_APP --resource-group $RESOURCE_GROUP --docker-custom-image-name $CONTAINER_REG.azurecr.io/$APP_NAME:latest
                "
            env:
              AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
              AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
              AZURE_TENANT_ID: $(AZURE_TENANT_ID)
              WEB_APP: $(WEB_APP)
              RESOURCE_GROUP: $(RESOURCE_GROUP)
              CONTAINER_REG: $(CONTAINER_REG)
              APP_NAME: $(APP_NAME)
              BUILD_ID: $(BUILD_ID)
            displayName: 'Deploy to Azure Web App using Azure CLI Docker Container'
