trigger:
  branches:
    include:
      - main

variables:
  APP_NAME: 'human-resources-service'
  CONTAINER_REG: 'salasmicroservicesacr'
  WEB_APP: 'api-integration-ms'
  RESOURCE_GROUP: 'data-management-group'
  TENANT_ID: '39f1381a-9292-4c9c-8aef-2e074e1569c2'
  BUILD_ID: $(Build.BuildId)

stages:
  - stage: Deploy
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy Docker Image to Azure Web App'
        pool:
          vmImage: 'ubuntu-latest'
        container: 'mcr.microsoft.com/azure-cli:latest'
        steps:
          - task: AzureCLI@2
            inputs:
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(TENANT_ID)
                az webapp config container set --name $(WEB_APP) --resource-group $(RESOURCE_GROUP) --docker-custom-image-name $(CONTAINER_REG).azurecr.io/$(APP_NAME):latest
            env:
              AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)  # Variable secreta configurada en Azure Pipelines
              AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
            displayName: 'Deploy to Azure Web App'
